### ISSUE TITLE
Allow specifying a custom font for the text in italic

### ISSUE THREAD

**Issue by matthieusieben** [one-dark/vscode-one-dark-theme#12]
This would allow to use this theme without having to create custom font files.

**Comment by mskelton** [comment]
What font do you use which is having issues with the italics?

**Comment by matthieusieben** [comment]
I wondered if it'd be possible to specify an alternete font to use for the text in italic. But as I understand it, it is not possible with vs-code 's internal API

**Comment by mskelton** [comment]
Yeah, this themes like something that probably isn't possible and even if it was it seems like a pretty edge case.
