### ISSUE TITLE
Italic for HTML Attributes

### ISSUE THREAD

**Issue by dorudumitru** [one-dark/vscode-one-dark-theme#17]
Is it possible to add italics for HTML Attributes?

Example:

One Dark
![vscode](https://user-images.githubusercontent.com/11142539/83098126-6c4f9880-a0b2-11ea-9f5a-4dd0c1884202.png)

Monokai
![vscode-monokai](https://user-images.githubusercontent.com/11142539/83098181-8f7a4800-a0b2-11ea-9f6d-4c67e6d6aef8.png)

**Comment by mskelton** [comment]
I'm open to this idea.  I'm waffling a bit if this should be a separate option or part of the main italic option.

**Comment by mskelton** [comment]
I decided to not make a separate option for this.  I'm making some pretty large changes to the theme and this will become part of those changes.
