### ISSUE TITLE
Color does not match up

### ISSUE THREAD

**Issue by dorudumitru-hh** [one-dark/vscode-one-dark-theme#26]
The blue color of text in the integrated terminal does not match up with the rest of the theme. It seems darker.

![image](https://user-images.githubusercontent.com/40240395/90895376-be127100-e3ca-11ea-8100-6d2123f0c4bf.png)
![image](https://user-images.githubusercontent.com/40240395/90895517-f74ae100-e3ca-11ea-98cb-34da842c5e0e.png)

**Comment by mskelton** [comment]
I'm not entirely sure, but I believe those colors are actually controlled by your terminal theme.  So if you are using zsh for example you will want to adjust it's colors to match with what you are expecting.
