### ISSUE TITLE
Comments font

### ISSUE THREAD

**Issue by DamagedDingo** [one-dark/vscode-one-dark-theme#34]
Can we change the comments font back or select one that readable? I looked around but couldn't see any options for this.

**Comment by mskelton** [comment]
@DamagedDingo I'm assuming you mean turning off the italics?  Or do you mean using a separate font for italics altogether?

**Comment by DamagedDingo** [comment]
The strange cursive font that appears. I can't read the r and S letters. Assuming I'm not stupid and it's coming from this plugin..

**Comment by mskelton** [comment]
If you hop into your settings and search for `One Dark: Italic`, you can disable the italics which should achieve your desired result.

<img width="996" alt="Screen Shot 2021-05-28 at 9 18 50 PM" src="https://user-images.githubusercontent.com/25914066/120053817-f26a2c00-bff1-11eb-96b4-2589ab654b2f.png">

**Comment by DamagedDingo** [comment]
Thanks!
