### ISSUE TITLE
Wrong violet in vscode integrated terminal

### ISSUE THREAD

**Issue by dorudumitru-hh** [one-dark/vscode-one-dark-theme#38]
vscode integrated terminal - one-dark-theme
![Screenshot 2021-11-16 at 12 12 10](https://user-images.githubusercontent.com/40240395/141966447-c25b6498-85d0-4294-ad29-7815f1164ca1.png)

iTerm terminal - one-dark-theme
![Screenshot 2021-11-16 at 12 12 29](https://user-images.githubusercontent.com/40240395/141966525-66c1a872-401e-4eac-adb7-83c935b0cc6c.png)

webstorm - one-dark-theme
![Screenshot 2021-11-16 at 12 17 13](https://user-images.githubusercontent.com/40240395/141967016-71cc9193-6a9f-41a4-a068-df3e17848b7b.png)

**Comment by mskelton** [comment]
Just pushed a commit that should fix this.
