### ISSUE TITLE
Cannot enable theme

### ISSUE THREAD

**Issue by klippx** [one-dark/vscode-one-dark-theme#5]
**Describe the bug**
Migrating from One Dark Pro Italic to One Dark Theme, the "set theme" isn't working.

**To Reproduce**

1. Install extension
2. Click Set Color Theme
3. Get toast "Cannot read property 'id' of undefined

**Expected behavior**
Take a guess :)

**Screenshots**
![Screenshot 2019-10-30 at 09 11 01](https://user-images.githubusercontent.com/2785359/67840010-37b43800-faf5-11e9-944f-654efc68acdf.png)

**Desktop (please complete the following information):**

- OS: Mojave 10.14.6
- VS Code Version [e.g. 1.39.2]

**Additional context**
Nope.

**Comment by mskelton** [comment]
Thanks for reporting this issue.  I have not noticed this at all when installing the new theme, so I'm a bit puzzled by it.  Could you try disabling other extensions and then installing it?  Also, if you open developer tools, is there more information in the console about the error?

Thanks!

**Comment by klippx** [comment]
When I tried again just to reproduce the error for you, I could not. I guess a relaunch of VSCode solved the issue, whatever it was. Closing this, thanks for the rapid response! :)

**Comment by mskelton** [comment]
Glad that the issue is fixed!
